name = "gpg"
version = "0.1.0"
license = "license"
author = "lukaswittmann"
maintainer = "mail@lukaswittmann.com"
copyright = "Copyright 2023, lukaswittmann"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
