name = "gpg"
version = "0.1.0"
license = "LGPL-3.0-or-later"
author = "lukaswittmann"
maintainer = "mail@lukaswittmann.com"
copyright = "Copyright 2023, lukaswittmann"
keywords = ["counterpoise", "computational-chemistry"]
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false

[dependencies]
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib.git"
